inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require: rubocop-rspec

Metrics/BlockLength:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

RSpec/ExampleLength:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

RSpec/NestedGroups:
  Enabled: false
